### ISSUE TITLE
Empty string values and "actionOnMissing: fail" cause the build to fail

### ISSUE THREAD

**Issue by JoeEnnever** [qetza/vsts-replacetokens-task#112]
We have a case in our pipeline where we want to replace a token with the empty string. However, when the `actionOnMissing: fail` setting is used with the task, the step fails. It would be great if the task would distinguish between unset variables and variables set to the empty string.

**Comment by qetza** [comment]
Hi @JoeEnnever,

Due to how the azure pipelines task typescript API works there is no way to distinguish between a none existing variable and an empty variable.

To work around this issue you can use a special value for your variable so that the task will replace this value by an empty string. The value is defined in the `Empty value`parameter in the `Advanced` group. The default he value is `(empty)`.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
