### ISSUE TITLE
File matching pattern has changed in v3.3.0

### ISSUE THREAD

**Issue by glasssd** [qetza/vsts-replacetokens-task#127]
In 3.2.2 and earlier, I could use most if not all of the file matching patterns here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/file-matching-patterns?view=azure-devops

For example for Target Files:
**/*.config
!**/RefreshMasterDb*/*.config
!**/TestSyncServiceForm/*.config

The negation in particular doesn't appear to be working in 3.3.0.
Can that portion be rolled back?

**Comment by qetza** [comment]
Hi @glasssd,

To be honest i never tested the exclude pattern :(

I took a look at the code and understand why it worked and why it’s not working anymore. I think i have a fix, i’ll test it and implement it this week-end. It will however need you to change your parameters to add a semi-colon between your pattern instead of a new line.

**Comment by qetza** [comment]
Hi @glasssd,
Version 3.3.1 is out and should fix your issue with the following syntax:
`/*.config;!/RefreshMasterDb*/.config;!**/TestSyncServiceForm/.config`

use `;` to separate the include pattern from the negative patterns

**Comment by glasssd** [comment]
Sorry for the delay in responding. I updated my configuration and the negative patterns worked as expected. Thank you so much for the very quick response.
