### ISSUE TITLE
Angular environment.ts boolean value token replacement

### ISSUE THREAD

**Issue by wazbekker** [qetza/vsts-replacetokens-task#158]
Hi

Thanks for the work you have put into this great task. 

I am hoping you can help me out with an issue I am having.

I have an environment.prod.ts file in an Angular application with a boolean value:

```typescript
export const environment = {
  production: false,
  oAuthConfig: {
    requireHttps: true
  }
}
```
which I would like to replace with a token:

```typescript
export const environment = {
  production: false,
  oAuthConfig: {
    requireHttps: '#{OAuthConfigRequireHttps}#'
  }
}
}
```

The token above needs to be in quotes or it causes a syntax error.  

I have tried searching for a solution and came across this SO post which didn't seem to work for me:
https://stackoverflow.com/questions/53087728/angular-azure-devopstfs-replace-tokens-in-environment-ts-file-environment

When the task runs it only replaces 7 of my 9 tokens and skips the boolean tokens that I would like to replace.

Any help with this would be greatly appreciated.

**Comment by qetza** [comment]
Hi @wazbekker,
Sorry for the late reply. The task do a "simple" search and replace in text files so if you set a variable `OAuthConfigRequireHttps` with the value `true` with the file:
```javascript
export const environment = {
  production: false,
  oAuthConfig: {
    requireHttps: #{OAuthConfigRequireHttps}#
  }
}
```

You should obtain:
```javascript
export const environment = {
  production: false,
  oAuthConfig: {
    requireHttps: true
  }
}
```

The issue here is that your `environment.prod.ts` will be invalid as a typescript file so may have issues at compile time.

That's why you can do this which should fix the typescript issue:
```javascript
export const environment = {
  production: false,
  oAuthConfig: {
    requireHttps: '#{OAuthConfigRequireHttps}#' === 'true'
  }
}
```

As for why only 7 out of 9 tokens are replaced, this means that some tokens where not found as variable, if you select detailed logs in the dropdown of the task you will have more info. You can also activate diagnostics logs at the pipeline run level.

**Comment by wazbekker** [comment]
Hi @qetza 

Thanks for the reply.

I tried what you suggested above and I also did some more research and I unfortunately don't think it is going to fit my use case.  

I am currently replacing tokens in my deployment pipeline in the main*.js file and not in the build pipeline.  The reason for this is I need to do one Production build for an application and then replace tokens on deployment for the different environments I will deploy to.  The problem with boolean values in the environment.ts files is that they get evaluated at build/compile time which means my string tokens will not be available in the main*.ts file to replace anymore. 

Thanks again for taking the time to reply and try help me out.
