### ISSUE TITLE
Add base64 encoding?

### ISSUE THREAD

**Issue by Davidsv** [qetza/vsts-replacetokens-task#163]
Can base64 encoding be added? Sometimes the replaced value can interfere with the overall file. In this particular case I am thinking about kubernetes secrets.

**Comment by qetza** [comment]
Hi @Davidsv,
Do you need all variables to be base64 encoded or only specific ones?

If you need only specific ones a quick workaround would be to do yourself the base64 encoding and store the result in your variable instead of the unencoded one (or add another variable).

As i'm thinking adding support for simple functions to transform variable values i could add a `tobase64` function, this would look like this : `#{ tobase64(my-variable-name) }#`.

**Comment by Davidsv** [comment]
@qetza Thanks for the reply,
I need almost all variables like this, so the workaround would not really be practical (and I don't own all the variables).
Regarding simple transform functions, if I can give a suggestion, to add an option in the task interface instead of/in addition to at the token level, to easily apply the transform to all matched tokens. Also it avoids need to change the files containing the token.

**Comment by qetza** [comment]
The new release now support the `base64` tranformation.
