### ISSUE TITLE
The task does NOT fail when a token value is missing 

### ISSUE THREAD

**Issue by ilonaChodnicka** [qetza/vsts-replacetokens-task#209]
Hello

I configured the task to fail when a token is missing 
2021-05-17T17:08:52.4697836Z ##[debug]actionOnMissing=fail
and it does NOT fail. 
This causes issues down the pipeline where values in config file(s) are missing. 

[replace_tokens_does_not_die.txt](https://github.com/qetza/vsts-replacetokens-task/files/6495629/replace_tokens_does_not_die.txt)

**Comment by qetza** [comment]
Hi @ilonaChodnicka,
The issue is with your configuration:

As you have set a default value `ERROR - MISSING TOKEN VALUE!!!!!!!`, if no variable is found then the task will use this default value which will then not be registered as a missing value. 
To resolve your issue just leave the default value parameter empty.

Also note that as you have set the empty value to `ERROR - MISSING TOKEN VALUE!!!!!!!` that is why the tokens are replace with empty strings.

You can see this in your logs:
```
2021-05-17T17:08:52.5920889Z ##[debug]FILE_SERVICE_WORKER_ENVIRONMENT_LABEL=undefined
2021-05-17T17:08:52.5921446Z ##[debug]  FILE_SERVICE_WORKER_ENVIRONMENT_LABEL:  (default value)
```

The first line indicates that no variable with the name `FILE_SERVICE_WORKER_ENVIRONMENT_LABEL` was found.
The second line indicates that the token `FILE_SERVICE_WORKER_ENVIRONMENT_LABEL` was replaced with an empty string (no value displayed) and that this value was taken from the default value parameter.

**Comment by ilonaChodnicka** [comment]
Yes [ FACEPALM ]. 

I just spent the morning learning everything about task output variables and how to test them, and how to make the whole pipeline abort when defaultValueCount is not zero. And then I realized "It is replacing missing token values with a default value - if I DON'T replace it, then, logically, it should croak because I want it to fail on missing tokens". And it did. Humbled and embarrassed, off I went to GIT Hub to withdraw this issue as "not a bug", and bam! you already explained the wrongness of my way. 

Please accept my sincere apologies. 

:) However, I have a rookie in our DevOps team and he was sitting through this entire adventure, watching me work through it and narrate every step. Wonderful learning experience.  

![misconfigured_task_01](https://user-images.githubusercontent.com/66924607/118695586-5d8a5600-b7db-11eb-8499-f4f710913947.jpg)

**Comment by ilonaChodnicka** [comment]
Yes [ FACEPALM ].

I just spent the morning learning everything about task output variables and how to test them, and how to make the whole pipeline abort when defaultValueCount is not zero. And then I realized "It is replacing missing token values with a default value - if I DON'T replace it, then, logically, it should croak because I want it to fail on missing tokens". And it did. Humbled and embarrassed, off I went to GIT Hub to withdraw this issue as "not a bug", and bam! you already explained the wrongness of my way.

Please accept my sincere apologies.

:) However, I have a rookie in our DevOps team and he was sitting through this entire adventure, watching me work through it and narrate every step. Wonderful learning experience.
![misconfigured_task_01](https://user-images.githubusercontent.com/66924607/118697558-6da33500-b7dd-11eb-8180-8ca704506bc4.jpg)
