### ISSUE TITLE
How to use this task with YAML pipeline where I have a variable template?

### ISSUE THREAD

**Issue by Atul-Moghe** [qetza/vsts-replacetokens-task#211]
In classic CD pipeline the task works perfectly fine for me. Since I have variables and variable groups attached to my CD pipeline which this task picks up and replaces with the token.

However, for YAML pipeline, this task doesn't work for me. I also check with variableFiles attribute but doesn't work. The task shows success with no replacements (like this message - "replaced 0 tokens out of 0 in 0 file(s) in 0.032 seconds.").

              steps:
                - task: replacetokens@3
                  inputs:
                    targetFiles: '**/*.json'
                    encoding: 'auto'
                    writeBOM: true
                    actionOnMissing: 'warn'
                    keepToken: false
                    tokenPrefix: '#'
                    tokenSuffix: '#'
                    useLegacyPattern: false
                    enableTransforms: false
                    enableTelemetry: true
                    variableFiles: 'templates/dev-variables1.yml'

Also it would be great if there is an example of external varibaleFile.

**Comment by qetza** [comment]
Hi @Atul-Moghe,
Based on your message there was no file found so not token replaced. If you enable debug logs you could see why no files were found.
Not sure it will change anything as you say the task is running but when using the task in YAML i'm using the task id `qetza.replacetokens.replacetokens-task.replacetokens@3`.

As for variable files, this allows you to define your variables in a file instead of as variables or in a variable group.
Here is an example of a YAML variable file:
```yaml
root: hello world!
array:
- scalar
- - scalar2
  - var: scalarArray
- obj:
    var: scalarObj
```

You have defined the variable separator as `.` then the task will have access to the following variables:
- `root` with value `hello world!` 
- `array.0` with value `scalar`
- `array.1.0` with value `scalar2`
- `array.1.1.var` with value `scalarArray`
- `array.2.obj.var` with value `scalarObj`

**Comment by Atul-Moghe** [comment]
Thanks @qetza, for your quick response! Yes, I realized that there is a problem with the file path which I have corrected and I am checking the results now.

Thanks for the variable samples, it's certainly helpful.

I'll update the comment once I have the results.

Thanks again!

**Comment by qetza** [comment]
Hi @Atul-Moghe,
Based on the logs the variable file is not found in the root directory. I think that the issue is in your `variableFiles` path, as it is not an absolute path it is relative to `rootDirectory` so the file path would be `$(System.DefaultWorkingDirectory)\../..\drop\LogicApp-CICD\templates\dev-variables.yml`.
Which in your case will give `D:\a\drop\LogicApp-CICD\templates\dev-variables.yml` 

Try having the variableFiles value to `drop\LogicApp-CICD\templates\dev-variables.yml`

**Comment by Atul-Moghe** [comment]
Thanks @qetza!

I couldn't manage to give the right path to variableFiles field (tried every different way including your suggested way). However, I could have my variables passed as Pipeline variables as below. It's working fine for me now. 

    jobs:
      - deployment: DevDeploy
        environment: 'development'
        pool:
          vmImage: 'vs2017-win2016'
        variables:
          - template: 'LogicApp-CICD/templates/dev-variables.yml'

        strategy:
          runOnce:
            deploy:
              steps:
                - task: replacetokens@3
                  inputs:
                    rootDirectory: '../'
                    targetFiles: '**/*.json'
                    encoding: 'auto'
                    writeBOM: true
                    actionOnMissing: 'warn'
                    keepToken: false
                    tokenPrefix: '#'
                    tokenSuffix: '#'                    
                    useLegacyPattern: false
                    enableTransforms: false
                    ##variableFiles: '$(System.DefaultWorkingDirectory)\../..\drop\LogicApp-CICD\templates\dev-variables.yml'
                    enableTelemetry: true

Thanks so much,
Atul
