### ISSUE TITLE
'VSTS_PUBLIC_VARIABLES' exceeds the maximum supported length

### ISSUE THREAD

**Issue by Thejaswini23** [qetza/vsts-replacetokens-task#224]
We see below warning in the AzDo Release pipeline 

##[warning]Environment variable 'VSTS_PUBLIC_VARIABLES' exceeds the maximum supported length. Environment variable length: 32800 , Maximum supported length: 32766

The Task completed with above warning and variables values did not get replaced.
Is there any Limit for variables that can be replaced in a pipeline.? Is there any limitation that could have caused this ?

**Comment by qetza** [comment]
Hi @Thejaswini23,
The issue is i think a limit on the system.

Every variable you have is set as an environment variable before a task is run and when a task queries for a variable value it is retrieved from the environment variable. As you have a variable value which exceeds the system limit for environment variable values (32766) the environment variable is not created and the value is not accessible by the replace token task.

To solve this issue you should reduce the size of your variable value.

**Comment by qetza** [comment]
Closing for long inactivity, feel free to reopen if needed.
