### ISSUE TITLE
Node 6 deprecation warning

### ISSUE THREAD

**Issue by brettzook** [qetza/vsts-replacetokens-task#228]
Hello,

I'm noticing this warning in the last day or two from the deployment logs when using the Replace Tokens task:

> This task uses Node 6 execution handler, which will be deprecated soon. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10. If you are the user - feel free to reach out to the owners of this task to proceed on migration.

It's working fine and doesn't seem urgent, just wanted to make you aware.

Thanks for a great tool.

**Comment by qetza** [comment]
Hi @brettzook,
Thanks for the info, i'll look at the implication of upgrading to node 10 and release a new version accordingly.

**Comment by qetza** [comment]
New versions of the task are released using Node10.

**Comment by qetza** [comment]
I'm reopening the issue because i had to revert to node6 as there was some issue with some on-premises installation. I will try to contact the MS team to see what are the solutions.

**Comment by gorziza** [comment]
Do you have news about this case?

**Comment by qetza** [comment]
Hi @gorziza,
I will have to create a new major version as using the new node10 execution handler is a breaking change. I'll try to work on it this week-end.

**Comment by FilBot3** [comment]
Seems Node10 is depricated too. Might as well shoot for the latest LTS of Node which is like Node 14.

* https://dev.azure.com/mseng/AzureDevOpsRoadmap/_workitems/edit/1888423

**Comment by qetza** [comment]
Thanks @FilBot3 for the heads up.
If there is a move to a newer version of node n 2022 i will then wait for this version to avoid having to generate again a new breaking version as currently this is just a warning and the task is still working.

**Comment by FilBot3** [comment]
It also seems like NodeJS 16 is current LTS. https://nodejs.org/en/about/releases/

**Comment by gitnubster** [comment]
Hi all,
 
The deprecation warning about Node 6 now mentions 31st of March 2022 in the build logs explicitly. 
And according to the features timeline [linked](https://docs.microsoft.com/en-us/azure/devops/release-notes/features-timeline) before by @FilBot3 shows that Node 10 will starting to be deprecated in 2022 Q1, as mentioned. But the Node 16 execution handler is not yet supported or in the near feature. At least, it's not mentioned in the same features timeline link, while Node 14 support is mentioned but on hold for over a year now. 

Administrators of a devops tenant can check the "Disable node 6 tasks" in Azure Devops, which will block any task using Node 6. See https://dev.azure.com/<TENANTNAME>/_settings/pipelinessettings

As harsh admins can break the task any moment, while MS will do that at 31st of March 2022, and Node 14 execution handler is still on hold since 2020, then Node 10 is currently the way to go.

I think Node 10 support will be extended some more months after 2022 Q1, while Node 16 would take at least another year before it's mentioned on the features timeline link above. So to have plenty of time to repair pipelines (if necessary), it would be appreciated to have a new version within a few months ;)

**Comment by ReneSchumacher** [comment]
I'd recommend moving to the Node10 handler. Currently, there is an internal discussion about whether a new handler is necessary at all, or if the node10 handler can simply use newer node versions in the future. The internal migration to Node10 is still going on and, according to the product group, moving to newer versions of Node.js is much easier as there aren't as many breaking changes as between Node6 and Node10.

**Comment by qetza** [comment]
Thanks @gitnubster and @ReneSchumacher for your insight,
I'll prepare a new major version of the task using the node10 handler and having the correct minimum agent version requirement.

**Comment by ReneSchumacher** [comment]
@qetza Afaik, you can have both handlers, the node and node10. The task will then prefer the node10 handler on newer systems and fall back to the node handler on older versions of TFS. Of course, this only works if you don't have to do code changes that are incompatible with Node.js 6.x. Might be worth testing, as it would not need a major version update.

**Comment by qetza** [comment]
@ReneSchumacher, the task has no incompatibility with node6 and node10. I've already tried to deploy a minor version with just the change to the handler (changed the execution handler to `Node10`) but this broke lots of builds as the minimum version of the agent currently supported by the task `2.105.0` didn't understood the new handler and i had to do a rollback.
I asked on the github of azure-pipelines-agent and they told me that the minimum agent version must be `2.144.0` so i need to do a new major version with this new requirement to avoid breaking changes. If you know any other configuration which would allow to keep the current minimum agent version to `2.105.0` i'm open to everthing 😄

**Comment by mpec** [comment]
@qetza any update on this? Do you plan to publish a new major version anytime soon?

**Comment by qetza** [comment]
New version 5 of the task was released which is executing on node10. Please be award that the v5 was based on the v4 so all breaking change of v4 applies to v5.
