### ISSUE TITLE
Replacing \\ in json file

### ISSUE THREAD

**Issue by evergrn435** [qetza/vsts-replacetokens-task#229]
Hi,

I have a variable value that includes a \\, but when it does the replacement it inputs \\\\. Is there a way to replace with \\

Thanks

**Comment by evergrn435** [comment]
If replacing in json it doubles it, from \\ to \\\\. When replacing in a txt file, it does not, from \\ to \\. I need the variable to replace the same way in both types of files. I am using in Azure DevOps pipeline.

**Comment by qetza** [comment]
Hi @evergrn435,
This behavior is because the `\` character needs to be escape in json value and the task automatically escape needed characters in json and xml files.
If you do not want any escaping in your file you can set the `Escape type` parameter to `none`. If you only want to disable escaping for some tokens you can use the transformation `noescape` around those tokens.

**Comment by evergrn435** [comment]
Thanks qetza. That worked! Appreciate your help!
