### ISSUE TITLE
Empty string in variable is saying variable not found and failing pipeline

### ISSUE THREAD

**Issue by rod-meaney** [qetza/vsts-replacetokens-task#263]
Hi,

We love the feature that allows the pipeline to fail if the variable is not there. However, if the variable is there but it is blank, it is failing. Is this intentional because we see it as a defect.

Our specific scenario is that we have a variable that represents non-prod environments in our build, and thus is is blank for production.

Many thanks

**Comment by qetza** [comment]
Hi @rod-meaney,
Yes the way the task is treating empty values is a little bit flawed due to some miss conception in its first versions.

Now this scenario is better managed but you need to switch to the new code by unchecking the parameter __Use legacy empty/default feature__ in the UI or setting the input __useLegacyEmptyFeature__ to false in YAML.

**Comment by rod-meaney** [comment]
Thanks - worked perfectly. Should have spotted it in the doco - we tried a few other things with no luck. Many thanks.
