### ISSUE TITLE
Environment File replacement issue

### ISSUE THREAD

**Issue by acuellarVB** [qetza/vsts-replacetokens-task#298]
Hello,

 I have been using your task for quiet some time now with no issues. Very grateful!

Recently I have been getting an error stating that a variable hasn't been found even though I have not changed any new variable configurations. Randomly started happening since 12/29

Very standard configuration set up 

![pipelineTask](https://user-images.githubusercontent.com/87141917/210666313-66d2414e-253a-4b7f-8079-d84e46fa16f2.png)
![image](https://user-images.githubusercontent.com/87141917/210666564-4c614dcc-8f42-4208-9174-ec2a1fcdf033.png)
Now throws a warning saying it cant find the second variable even though nothing was changed. 

Causes a regex error on dev server when deployed.

Any idea what could have changed?

Thank you

**Comment by qetza** [comment]
Hi @acuellarVB,
Based on your screenshot I would say that the regex used by the task to find tokens is not detecting correctly the token due to your code maybe generating text which looks like the token prefix.
You could try using another token pattern which might have less chance of being generate by your code.

**Comment by acuellarVB** [comment]
Thanks that worked great!
