### ISSUE TITLE
Can't downgrade to 1.4.1

### ISSUE THREAD

**Issue by mrichman** [qetza/vsts-replacetokens-task#33]
I removed the newer version (I'm on TFS 2015) and tried to install 1.4.1. Getting the error:

> A task definition with id 'a8515ec8-7254-4ffd-912c-86772e2b5962' has already been uploaded. To replace the existing definition, provide a task version which is greater than '2.0.1'.

![image](https://cloud.githubusercontent.com/assets/11228/25200401/3864bbaa-251c-11e7-95aa-568d986fb7ab.png)

![image](https://cloud.githubusercontent.com/assets/11228/25200408/3be14f1e-251c-11e7-880e-a929e55ca9ad.png)

**Comment by qetza** [comment]
Hi Mark,
Did you uninstall the version 2.0.1 first?

I'll see with Microsoft if there is a way to downgrade or fix the issue.

**Comment by qetza** [comment]
Hi Mark,

Could you give me some more information on which version of TFS you are using (including update) and how you installed/uninstalled the extension in it's different versions?

I've done the following test on a TFS 2015 update 3 and didn't have an issue:
- Install extension v2.0.2 on the local gallery
- Install the extension in a collection
- Validate that the task was not displayed in the list of available task (because of incompatibility)
- Uninstall the extension from the local gallery
- Install the extension v1.4.1 on the local gallery
- Install the extension in a collection
- Create a build definition with the task and run it

Thanks
