### ISSUE TITLE
Add ability to provide default value in placeholder

### ISSUE THREAD

**Issue by yar-shukan** [qetza/vsts-replacetokens-task#49]
Hello.

Awesome TFS extension!

One small issue that we faced with: we have lot's of environments (more than 100). And we have a rule to fail on missing variable.
So the problem is to add new variable. We frequently have a situation to add new variable like $(MyNewVariable) that is "True" for 99 envs, but "False" for only one.
But we also don't want to go to 99 envs and put "True" there. What we want is to have ability define default like that:
$(MyNewVariable|True)
$(MyOtherVariable|http://defaultsite.com)

So if there's no variable defined - the "True" will go by default (for second example it will be http://defaultsite.com).

The separator ("|" in my example) can be anything (so it can be "|" by default or user can pass it in TFS if he wants).

@qetza do you find any objections regarding adding that functionality?

Thanks

**Comment by qetza** [comment]
Hi @yar-shukan,
From what i understand of your issue this can be resolved in VSTS directly.

If you have only one release definition with all your environments, just declare your variable MyNewVariable at the release scope with the value True and for your special environment declare it as False. As VSTS already support priority on variable scope (a variable declare at envionment scope will be used instead of the value declared at release scope) it will work.

If you have multiple release definitions use variable groups to define your common variables with default values and override them at release or environment scope. Again VSTS priority is environment > release > group

Hope this will help you.
