### ISSUE TITLE
Request:  Verbose logging

### ISSUE THREAD

**Issue by argrithmag** [qetza/vsts-replacetokens-task#60]
I would love to see an option to do "Verbose" logging, that is, log the line number, token name and replaced value when it's actually replaced, in addition to the log info of skipped variables.  

Great plugin!  I had a sketchy powershell script I was able to replace with this!

**Comment by qetza** [comment]
Hi @argrithmag,

Thanks for the feedback.

There are already verbose logs. You activate them by defining a `system.debug` variable with the value `true`. This will output all found token with their replace value. It won't display the line number because the task is not doing a line by line replacement but just using a regular expression to find all tokens.
