### ISSUE TITLE
When installing 2.x version to TFS 2015 U4 build step is not visible

### ISSUE THREAD

**Issue by Arturas-K** [qetza/vsts-replacetokens-task#69]
Hi,

It looks like there is an issue with 2.0.0 and later version of extension when installing on TFS 2015 Update 3.
It uploads successfully, and install to collection successfully also.
But it is not visible in build tasks list.

I have tried all previous versions and 1.4.1 version installs correctly.

Furthermore if i then update from 1.4.1 to 2.3.0 (Latest at the time of writing) step remains visible.

It looks to me that some registration in 2.x version is not compatible with TFS 2015.

**Comment by qetza** [comment]
Hi Arturas,
The v2 of the task was rewritten in typescript to be compatible with linux agents but this need a 2.105.0 build agent at least which is not available in TFS 2015. That's why the task is hidden under TFS 2015.
As written in the release notes, if you need this task on TFS 2015 you have to install version 1.4.1
